FROM node:22

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

ARG PORT
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME
ARG AUTH0_CLIENT_ID
ARG AUTH0_ISSUER_BASE_URL
ARG AUTH0_CLIENT_SECRET
ARG AUTH0_BASE_URL
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_BUCKET_NAME
ARG CLOUD_FRONT_DOMAIN

ENV PORT=$PORT \
    DB_HOST=$DB_HOST \
    DB_PORT=$DB_PORT \
    DB_USERNAME=$DB_USERNAME \
    DB_PASSWORD=$DB_PASSWORD \
    DB_NAME=$DB_NAME \
    AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID \
    AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL \
    AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET \
    AUTH0_BASE_URL=$AUTH0_BASE_URL \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_REGION=$AWS_REGION \
    AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
    CLOUD_FRONT_DOMAIN=$CLOUD_FRONT_DOMAIN

COPY . .

RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production

CMD ["npm","start"]
